#
# Basic settings.
#
#url: http://localhost:4000
# baseurl: ""
url: http://david.twinklebob.co.uk
baseurl: ""
title: David Lumm
description: Christian, Father, Husband, Geek, Programming Wizard
#avatar: /assets/img/ogp.png
avatar: //www.gravatar.com/avatar/10d0a7cca3e3839297b1e5050c165dc4.jpg?s=200
# favicon: /favicon.ico
favicon: //www.gravatar.com/avatar/10d0a7cca3e3839297b1e5050c165dc4.png?s=200
# language: ja
language: en
future: false

#
# Icons
#
icons:
  behance:
  bitbucket: cyberneticiandave
  dribbble:
  email:
  facebook: david.lumm
  flickr:
  github: twinklebob
  goodreads: cyberneticiandave
  google_plus: +DavidLumm
  instagram: cyberneticiandave
  linkedin: https://www.linkedin.com/in/davidlumm/ # full URL
  nextfree: https://www.nextfree.co.uk/for/david-lumm
  pinterest: gorthelyk
  reddit: CyberneticianDave
  rss: true
  soundcloud:
  stack_exchange: https://stackexchange.com/users/550385/cyberneticiandave # full URL
  steam:
  tumblr:
  twitter: CyberneticDave
  wordpress:
  youtube: CyberneticianDave

#
# Prettify url.
#
permalink: pretty

#
# Scripts.
#
google_analytics: UA-96377337-1 # e.g. UA-000000-01
disqus:

#
# Localizations.
#
str_next: Next
str_prev: Prev
str_read_more: Read more...
str_search: Search
str_recent_posts: Recent posts
str_show_all_posts: Show all posts

#
# Recent posts.
#
recent_posts_num: 10

#
# Pagination.
#
paginate: 10
paginate_path: page/:num

#
# Social.
#
share_buttons:
  twitter: true
  facebook: true # needs ogp.fb.app_id
  hatena: false
ogp:
  image_url: https://www.gravatar.com/avatar/10d0a7cca3e3839297b1e5050c165dc4.png?s=600
  fb:
    admin: david.lumm # facebook admin id
    app_id: 139176982849302 # facebook application id

wpm: 180

#
# Gems.
#
gems:
  - jekyll-paginate
  - jemoji
  - jekyll-sitemap

#
# Styles: see "_sass/base/_variables.scss"
#

#
# !! Danger zone !!
#

include: ["_pages"]

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

excerpt_separator: <!--more-->

sass:
  sass_dir: _sass
  style: :compressed # or :expanded

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor
